export const OurTreatments = [
  {
    slug: "ramaiah-institute-oncosciences",
    title: "Services & Facilities",
    items: [
      "Outpatient Services",
      "Inpatient Wards",
      "Daycare Chemotherapy Units",
      "Radiation Therapy",
      "Robotic & Laparoscopic Oncosurgery",
      "Genetic Counselling",
      "PET-CT",
      "Laboratory",
      "Pharmacy",
    ],
  },
  {
    slug: "ramaiah-institute-oncosciences/medical-oncology",
    title: "Services & Facilities",
    items: [
      "Pediatric Oncology",
      "Hemato Oncology",
      "Solid Tumor Oncology",
      "Chemotherapy",
      "Immunotherapy ",
      "Targeted Therapy",
      "Bone Marrow Transplant (Autologous, Allogenic, Haplo-identical) ",
      "CAR-T Cell Therapy ",
      "Integrative Oncology / Palliative care",
      "Benign Hematology",
    ],
  },
  {
    slug: "ramaiah-institute-oncosciences/surgical-oncology",
    title: "Services & Facilities",
    items: [
      "Head & Neck Oncosurgery",
      "Breast Oncosurgery ",
      "Gastrointestinal Oncosurgery",
      "Robotic Oncosurgery",
      "Gynec Oncosurgery ",
      "Thoracic Oncosurgery ",
      "HPB Oncosurgery ",
      "Laparoscopic Oncosurgery ",
      "Ortho Oncosurgery ",
      "CRS – HIPEC, PIPEC ",
    ],
  },
  {
    slug: "ramaiah-institute-oncosciences/radiation-oncology",
    title: "Services & Facilities",
    items: [
      "Image Guided Radiotherapy (IGRT) ",
      "Volumetric Modulated Arc Radiotherapy (VMAT)",
      "Intensity Modulated Radiotherapy (IMRT) ",
      "3-Dimensional Radiotherapy (3D-RT) ",
      "Conventional / Palliative Therapy",
      "Stereotactic Body Radiation Therapy",
      "Total Body Irradiation ",
      "Total Skin Electron Therapy",
      "Intraoperative Radiation Therapy (IORT)",
      "HDR Brachytherapy",
      "Stereotactic Radiosurgery",
    ],
  },
  {
    slug: "ramaiah-institute-oncosciences/hemato-oncology",
    title: "Services & Facilities",
    items: [
      "Autologous Stem Cell Transplant",
      "Allogeneic Bone Marrow Transplantation",
      "Haploidentical Bone Marrow Transplantation",
      "Reduced Intensity Bone Marrow Transplantation",
      "Haploidentical Stem Cell Transplantation",
      "Umbilical Cord Blood (UCB) Allogeneic Bone Marrow Transplantation",
      "CAR-T Cell Therapy for Hematological Malignancies",
    ],
  },
  {
    slug: "ramaiah-institute-oncosciences/nuclear-medicine",
    title: "Services & Facilities",
    items: [
      "PET CT ",
      "Gamma Camera ",
      "Nuclear Therapies",
    ],
  },

  {
    slug: "anaesthesiology",
    title: "Our Treatment & Procedure",
    items: [
      "General Anaesthesia",
      "Regional Anesthesia",
      "Monitored Anesthesia Care",
      "Conscious Sedation",
      "Labour Analgesia",
      "Neuro and Cardiac Anesthesia",
      "Ultrasound guided nerve blocks",
      "Pain Management *",
      "Low Back Pain Chronic Post Surgical Pain",
      "Neck Pain Knee Pain",
      "Facial Pain Complex Regional Pain Syndrome",
      "Nerve Pain Syndromes Musculoskeletal Pain",
      "Cancer Pain Foot pain and Plantar Fasciitis",
      "Shoulder Pain Headaches",
    ],
  },
  {
    slug: "cardiology",
    title: "Our Treatment & Procedure",
    items: [
      "Non Invasive Lad – 2D transthoracic and transesophageal echo, DSE, STE, Contrast Echo",
      "Interventional Cardiology – Cardiac catheterization, angioplasty, complex hybrid intervention procedures (CHIP) including rotablation, IVL; intracoronary physiology and imaging, high risk protected PCI including Impella based procedures",
      "Structural interventions – TAVI, PTMC",
      "Cardiac Devices",
      "Pacemakers – conduction system pacing, leadless pacemakers, ICD, CRT based devices",
      "Cardiac electrophysiology – EPS + RFA of both simple and complex arrhythmias, PVI for atrial fibrillation, VT ablation",
      "Advanced heart failure management including ECMO, VAD & Transplant",
      "Womens Health and preventive cardiology",
    ],
  },
  {
    slug: "center-for-rehabilitation",
    title: "Our Treatment & Procedure",
    items: [
      "Back pain",
      "Neck pain",
      "Frozen shoulder",
      "Arthritis",
      "Post fracture rehabilitation",
      "Ligament and soft tissue injuries",
      "Post joint replacement Rehabilitation",
      "Poor Postures",
      "Repetitive strain Injuries",
      "Tennis elbow",
      "Plantar Fasciitis",
    ],
  },
  {
    slug: "cardiothoracic-surgery",
    title: "Our Treatment & Procedure",
    items: [
      "MICS-Minimal Invasive Cardiac Surgery",
      "Valve Repair/ Preplacements",
      "Heart Transplant",
      "ECMO",
      "VAD",
      "All Congenital Heart Surgery",
      "Thoracic Surgery",
    ],
  },
  {
    slug: "dental-surgery",
    title: "Our Treatment & Procedure",
    items: [
      "Stainless Steel Crowns",
      "Glass Ionomer Fillings with Light Cure",
      "Tooth Colored Fillings (Composite Resin",
      "X-Rays (Radiographs)",
      "Dental Cleaning (Prophylaxis)",
      "Fluoride Application",
      "Pit and fissure Sealants",
      "Early (Interceptive) Orthodontic Care",
      "Extractions (Tooth Removal)",
      "Root canal Therapy, root canal re-treatment fixing cracked teeth",
      "Managing trauma",
      "Regenerative endodontic procedures",
      "Internal bleaching",
      "Smile makeovers Dentures",
    ],
  },
  {
    slug: "dermatology-cosmetology",
    title: "Our Treatment & Procedure",
    items: [
      "Simple bed side diagnostic procedures like Grams stain, Tzanck smear, skin scrapings, Koh mount, Nail scraping/ clippings and Dark field microscopy.",
      "Electrocautery and Radiofrequency ablation",
      "Acne surgeries: Subcision, punch elevation, punch floatation, punch grafting and laser scar revision",
      "Vitiligo surgeries : mini punch grafting, blister grafting and Non-cultured epidermal cell suspension",
      "Partial and complete nail avulsion ",
      "Skin and Nail biopsies.",
      "Cryotherapy of Benign, premalignant and malignant skin disorders",
      "Whole body, hand and foot and Targeted phototherapy",
      "Laser tattoo removal for pigmentary disorders",
      "Laser hair removal",
      "Fractional co2 laser ablation for skin rejuvenation and acne scar revision",
      "Co2 laser ablation",
      "Botox and fillers.",
      "Skin intralesional injection and Nail intramatricial injectio",
      "Chemical peels",
    ],
  },
  {
    slug: "endocrinology",
    title: "Our Treatment & Procedure",
    items: [
      "Type 1 Diabetes mellitus",
      "Type 2 Diabetes mellitus",
      "Diabetes in pregnancy",
      "Obesity and lipid disorders",
      "Polycystic ovarian disease and other reproductive endocrine disorders including male and female infertility",
      "Pituitary diseases",
      "Cushing and Addison disease and other adrenal disorders",
      "Thyroid disorders and thyroid cancer",
      "Pediatric and Adolescent Endocrinology disorders including disorders of growth, puberty and sexual development",
      "Osteoporosis and Metabolic bone diseases",
      "Transgender medicine",
    ],
  },
  {
    slug: "ent",
    title: "Our Treatment & Procedure",
    items: [
      "Type 1 Diabetes mellitus",
      "Type 2 Diabetes mellitus",
      "Diabetes in pregnancy",
      "Obesity and lipid disorders",
      "Polycystic ovarian disease and other reproductive endocrine disorders including male and female infertility",
      "Pituitary diseases",
      "Cushing and Addison disease and other adrenal disorders",
      "Thyroid disorders and thyroid cancer",
      "Pediatric and Adolescent Endocrinology disorders including disorders of growth, puberty and sexual development",
      "Osteoporosis and Metabolic bone diseases",
      "Transgender medicine",
    ],
  },
  {
    slug: "general-medicine",
    title: "Our Treatment & Procedure",
    items: [
      "Parenteral and oral antimicrobials like antibiotics, antimalarials, anti helminthic, antivirals and anti fungal agents. COVID treatment of all categories of severity",
      "Oral antidiabetic agents, insulin, thyroxine, antihypertensives, heart failure treatment",
      "High dose Pulse steroid therapy, Transfusion of all blood components",
      "Immunomodulators and DMARDS",
      "Counselling sessions, anti delirium tremens therapy",
      "All adult vaccines",
      
    ],
  },
  {
    slug: "general-surgery",
    title: "Our Treatment & Procedure",
    items: [
      "Parenteral and oral antimicrobials like antibiotics, antimalarials, anti helminthic, antivirals and anti fungal agents. COVID treatment of all categories of severity",
      "Oral antidiabetic agents, insulin, thyroxine, antihypertensives, heart failure treatment",
      "High dose Pulse steroid therapy, Transfusion of all blood components",
      "Immunomodulators and DMARDS",
      "Counselling sessions, anti delirium tremens therapy",
      "All adult vaccines",
      
    ],
  },
];

export function getOurTreatmentsPage(slug) {
  return OurTreatments.find((dept) => dept.slug === slug);
}
