export const OurTreatments = [
  {
    slug: "anaesthesiology",
    items: [
      "General Anaesthesia",
      "Regional Anesthesia",
      "Monitored Anesthesia Care",
      "Conscious Sedation",
      "Labour Analgesia",
      "Neuro and Cardiac Anesthesia",
      "Ultrasound guided nerve blocks",
      "Pain Management *",
      "Low Back Pain Chronic Post Surgical Pain",
      "Neck Pain Knee Pain",
      "Facial Pain Complex Regional Pain Syndrome",
      "Nerve Pain Syndromes Musculoskeletal Pain",
      "Cancer Pain Foot pain and Plantar Fasciitis",
      "Shoulder Pain Headaches",
    ],
  },
  {
    slug: "cardiology",
    items: [
      "Non Invasive Lad – 2D transthoracic and transesophageal echo, DSE, STE, Contrast Echo",
      "Interventional Cardiology – Cardiac catheterization, angioplasty, complex hybrid intervention procedures (CHIP) including rotablation, IVL; intracoronary physiology and imaging, high risk protected PCI including Impella based procedures",
      "Structural interventions – TAVI, PTMC",
      "Cardiac Devices",
      "Pacemakers – conduction system pacing, leadless pacemakers, ICD, CRT based devices",
      "Cardiac electrophysiology – EPS + RFA of both simple and complex arrhythmias, PVI for atrial fibrillation, VT ablation",
      "Advanced heart failure management including ECMO, VAD & Transplant",
      "Womens Health and preventive cardiology",
    ],
  },
  {
    slug: "center-for-rehabilitation",
    items: [
      "Back pain",
      "Neck pain",
      "Frozen shoulder",
      "Arthritis",
      "Post fracture rehabilitation",
      "Ligament and soft tissue injuries",
      "Post joint replacement Rehabilitation",
      "Poor Postures",
      "Repetitive strain Injuries",
      "Tennis elbow",
      "Plantar Fasciitis",
    ],
  },
  {
    slug: "cardiothoracic-surgery",
    items: [
      "MICS-Minimal Invasive Cardiac Surgery",
      "Valve Repair/ Preplacements",
      "Heart Transplant",
      "ECMO",
      "VAD",
      "All Congenital Heart Surgery",
      "Thoracic Surgery",
    ],
  },
  {
    slug: "dental-surgery",
    items: [
      "Stainless Steel Crowns",
      "Glass Ionomer Fillings with Light Cure",
      "Tooth Colored Fillings (Composite Resin",
      "X-Rays (Radiographs)",
      "Dental Cleaning (Prophylaxis)",
      "Fluoride Application",
      "Pit and fissure Sealants",
      "Early (Interceptive) Orthodontic Care",
      "Extractions (Tooth Removal)",
      "Root canal Therapy, root canal re-treatment fixing cracked teeth",
      "Managing trauma",
      "Regenerative endodontic procedures",
      "Internal bleaching",
      "Smile makeovers Dentures",
    ],
  },
  {
    slug: "dermatology-cosmetology",
    items: [
      "Simple bed side diagnostic procedures like Grams stain, Tzanck smear, skin scrapings, Koh mount, Nail scraping/ clippings and Dark field microscopy.",
      "Electrocautery and Radiofrequency ablation",
      "Acne surgeries: Subcision, punch elevation, punch floatation, punch grafting and laser scar revision",
      "Vitiligo surgeries : mini punch grafting, blister grafting and Non-cultured epidermal cell suspension",
      "Partial and complete nail avulsion ",
      "Skin and Nail biopsies.",
      "Cryotherapy of Benign, premalignant and malignant skin disorders",
      "Whole body, hand and foot and Targeted phototherapy",
      "Laser tattoo removal for pigmentary disorders",
      "Laser hair removal",
      "Fractional co2 laser ablation for skin rejuvenation and acne scar revision",
      "Co2 laser ablation",
      "Botox and fillers.",
      "Skin intralesional injection and Nail intramatricial injectio",
      "Chemical peels",
    ],
  },
  {
    slug: "endocrinology",
    items: [
      "Type 1 Diabetes mellitus",
      "Type 2 Diabetes mellitus",
      "Diabetes in pregnancy",
      "Obesity and lipid disorders",
      "Polycystic ovarian disease and other reproductive endocrine disorders including male and female infertility",
      "Pituitary diseases",
      "Cushing and Addison disease and other adrenal disorders",
      "Thyroid disorders and thyroid cancer",
      "Pediatric and Adolescent Endocrinology disorders including disorders of growth, puberty and sexual development",
      "Osteoporosis and Metabolic bone diseases",
      "Transgender medicine",
    ],
  },
  {
    slug: "ent",
    items: [
      "Type 1 Diabetes mellitus",
      "Type 2 Diabetes mellitus",
      "Diabetes in pregnancy",
      "Obesity and lipid disorders",
      "Polycystic ovarian disease and other reproductive endocrine disorders including male and female infertility",
      "Pituitary diseases",
      "Cushing and Addison disease and other adrenal disorders",
      "Thyroid disorders and thyroid cancer",
      "Pediatric and Adolescent Endocrinology disorders including disorders of growth, puberty and sexual development",
      "Osteoporosis and Metabolic bone diseases",
      "Transgender medicine",
    ],
  },
  {
    slug: "general-medicine",
    items: [
      "Parenteral and oral antimicrobials like antibiotics, antimalarials, anti helminthic, antivirals and anti fungal agents. COVID treatment of all categories of severity",
      "Oral antidiabetic agents, insulin, thyroxine, antihypertensives, heart failure treatment",
      "High dose Pulse steroid therapy, Transfusion of all blood components",
      "Immunomodulators and DMARDS",
      "Counselling sessions, anti delirium tremens therapy",
      "All adult vaccines",
      
    ],
  },
  {
    slug: "general-surgery",
    items: [
      "Parenteral and oral antimicrobials like antibiotics, antimalarials, anti helminthic, antivirals and anti fungal agents. COVID treatment of all categories of severity",
      "Oral antidiabetic agents, insulin, thyroxine, antihypertensives, heart failure treatment",
      "High dose Pulse steroid therapy, Transfusion of all blood components",
      "Immunomodulators and DMARDS",
      "Counselling sessions, anti delirium tremens therapy",
      "All adult vaccines",
      
    ],
  },
];

export function getOurTreatmentsPage(slug) {
  return OurTreatments.find((dept) => dept.slug === slug);
}
